# python -m train --config-name=c4_a100x8x4_37m +paths.model_name=270m
defaults:
  - starcoder_base
  - _self_

num_hosts: 4

mesh:
  d: 16
  t: 1

training:
  warmup_steps: 240
  steps:        2400
  steps_for_lr: 2400
  learning_rate: 1.35e-2
  tokens:
    length: 2048
    batch: 256
  use_grad_clip: true
  use_gpu: false
  use_single_pod: false

model:
  d_model: 256
  n_q_per_kv: 1
  n_kv: 16
  d_head: 64
  d_ff: 1024
  layers: 8
  vocab: 32768

  base:
    d_model: 256
    n_q_per_kv: 1
    n_kv: 16
    d_head: 64
    d_ff: 1024

  rope_max_timescale: 10000

  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true

  parameterization: "sp"
  fully_aligned: false
  gamma_embed: 1.
  gamma_hidden: 1.
  gamma_unembed: 1.

checkpoint_interval: 9200

hf_dataset:
  num_workers: 8