# python -m train --config-name=c4_a100x8x4_10m +paths.model_name=270m
defaults:
- synthetic_base
- _self_

num_hosts: 1

mesh:
  d: 1 
  t: 1

training:
  warmup_steps: 250
  steps:        2500
  steps_for_lr: 2500
  learning_rate: 5.0e-3
  tokens:
    len: 128
    batch: 256
  use_grad_clip: true
  use_gpu: true

model:
  d_model: 128
  n_q_per_kv: 1
  n_kv: 16 
  d_head: 32 
  layers: 8
  d_ff: 512 
  vocab: 49 
  rope_max_timescale: 10000
  a_attn: 1.
  a_output: 1.
  zero_queries: true
  zero_unembed: true
  base:
    d_model: 128
    n_q_per_kv: 1
    n_kv: 16 
    d_head: 32 
    d_ff: 512 
  parameterization: "sp" 
  fully_aligned: false
  gamma_embed: 1. 
  gamma_hidden: 1. 
  gamma_unembed: 1.
  
checkpoint_interval: 9200
